name: Test Calculate Temp R

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-calculate-temp-r:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.x'
    
    - name: Install renv and dependencies
      run: |
        # Install and initialize renv
        Rscript -e 'install.packages("renv")'
        Rscript -e 'renv::restore()'
        
    - name: Create Measurements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python createMeasurements.py
    
    - name: Run Calculate Temp R
      run: |
        # Compute the execution time for calculate_Temp.R
        start=$(date +%s.%N)
        Rscript calculate_Temp.R
        end=$(date +%s.%N)
        
        # Calculate elapsed time using bc
        runtime=$(echo "$end - $start" | bc)
        echo "Rscript calculate_Temp.R ran in ${runtime} seconds."
    
    - name: Compare Results
      run: |
        git diff --no-index --word-diff=porcelain .github/test/test_r.txt result_R.txt 
